/*
 * Copyright 2009-2015 DigitalGlobe, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mrgeo-core/src/main/proto/FileFormat.proto

package org.mrgeo.vector.mrsvector.pbf;

public final class FileFormat {
  private FileFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BlobOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes raw = 1;
    boolean hasRaw();
    com.google.protobuf.ByteString getRaw();
    
    // optional int32 raw_size = 2;
    boolean hasRawSize();
    int getRawSize();
    
    // optional bytes zlib_data = 3;
    boolean hasZlibData();
    com.google.protobuf.ByteString getZlibData();
    
    // optional bytes lzma_data = 4;
    boolean hasLzmaData();
    com.google.protobuf.ByteString getLzmaData();
    
    // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
    @java.lang.Deprecated boolean hasOBSOLETEBzip2Data();
    @java.lang.Deprecated com.google.protobuf.ByteString getOBSOLETEBzip2Data();
  }
  public static final class Blob extends
      com.google.protobuf.GeneratedMessage
      implements BlobOrBuilder {
    // Use Blob.newBuilder() to construct.
    private Blob(Builder builder) {
      super(builder);
    }
    private Blob(boolean noInit) {}
    
    private static final Blob defaultInstance;
    public static Blob getDefaultInstance() {
      return defaultInstance;
    }
    
    public Blob getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_Blob_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_Blob_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes raw = 1;
    public static final int RAW_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString raw_;
    public boolean hasRaw() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getRaw() {
      return raw_;
    }
    
    // optional int32 raw_size = 2;
    public static final int RAW_SIZE_FIELD_NUMBER = 2;
    private int rawSize_;
    public boolean hasRawSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getRawSize() {
      return rawSize_;
    }
    
    // optional bytes zlib_data = 3;
    public static final int ZLIB_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString zlibData_;
    public boolean hasZlibData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.google.protobuf.ByteString getZlibData() {
      return zlibData_;
    }
    
    // optional bytes lzma_data = 4;
    public static final int LZMA_DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString lzmaData_;
    public boolean hasLzmaData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getLzmaData() {
      return lzmaData_;
    }
    
    // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
    public static final int OBSOLETE_BZIP2_DATA_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString oBSOLETEBzip2Data_;
    @java.lang.Deprecated public boolean hasOBSOLETEBzip2Data() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    @java.lang.Deprecated public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
      return oBSOLETEBzip2Data_;
    }
    
    private void initFields() {
      raw_ = com.google.protobuf.ByteString.EMPTY;
      rawSize_ = 0;
      zlibData_ = com.google.protobuf.ByteString.EMPTY;
      lzmaData_ = com.google.protobuf.ByteString.EMPTY;
      oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, raw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rawSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, zlibData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, lzmaData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, oBSOLETEBzip2Data_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, raw_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rawSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, zlibData_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, lzmaData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, oBSOLETEBzip2Data_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_Blob_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_Blob_fieldAccessorTable;
      }
      
      // Construct using org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        raw_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        rawSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        zlibData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        lzmaData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.getDescriptor();
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob getDefaultInstanceForType() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.getDefaultInstance();
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob build() {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob buildPartial() {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob result = new org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.raw_ = raw_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rawSize_ = rawSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.zlibData_ = zlibData_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.lzmaData_ = lzmaData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.oBSOLETEBzip2Data_ = oBSOLETEBzip2Data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob) {
          return mergeFrom((org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob other) {
        if (other == org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.getDefaultInstance()) return this;
        if (other.hasRaw()) {
          setRaw(other.getRaw());
        }
        if (other.hasRawSize()) {
          setRawSize(other.getRawSize());
        }
        if (other.hasZlibData()) {
          setZlibData(other.getZlibData());
        }
        if (other.hasLzmaData()) {
          setLzmaData(other.getLzmaData());
        }
        if (other.hasOBSOLETEBzip2Data()) {
          setOBSOLETEBzip2Data(other.getOBSOLETEBzip2Data());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              raw_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rawSize_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              zlibData_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              lzmaData_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              oBSOLETEBzip2Data_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes raw = 1;
      private com.google.protobuf.ByteString raw_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasRaw() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getRaw() {
        return raw_;
      }
      public Builder setRaw(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        raw_ = value;
        onChanged();
        return this;
      }
      public Builder clearRaw() {
        bitField0_ = (bitField0_ & ~0x00000001);
        raw_ = getDefaultInstance().getRaw();
        onChanged();
        return this;
      }
      
      // optional int32 raw_size = 2;
      private int rawSize_ ;
      public boolean hasRawSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getRawSize() {
        return rawSize_;
      }
      public Builder setRawSize(int value) {
        bitField0_ |= 0x00000002;
        rawSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearRawSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rawSize_ = 0;
        onChanged();
        return this;
      }
      
      // optional bytes zlib_data = 3;
      private com.google.protobuf.ByteString zlibData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasZlibData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.google.protobuf.ByteString getZlibData() {
        return zlibData_;
      }
      public Builder setZlibData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        zlibData_ = value;
        onChanged();
        return this;
      }
      public Builder clearZlibData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zlibData_ = getDefaultInstance().getZlibData();
        onChanged();
        return this;
      }
      
      // optional bytes lzma_data = 4;
      private com.google.protobuf.ByteString lzmaData_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasLzmaData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getLzmaData() {
        return lzmaData_;
      }
      public Builder setLzmaData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        lzmaData_ = value;
        onChanged();
        return this;
      }
      public Builder clearLzmaData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        lzmaData_ = getDefaultInstance().getLzmaData();
        onChanged();
        return this;
      }
      
      // optional bytes OBSOLETE_bzip2_data = 5 [deprecated = true];
      private com.google.protobuf.ByteString oBSOLETEBzip2Data_ = com.google.protobuf.ByteString.EMPTY;
      @java.lang.Deprecated public boolean hasOBSOLETEBzip2Data() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      @java.lang.Deprecated public com.google.protobuf.ByteString getOBSOLETEBzip2Data() {
        return oBSOLETEBzip2Data_;
      }
      @java.lang.Deprecated public Builder setOBSOLETEBzip2Data(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        oBSOLETEBzip2Data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Deprecated public Builder clearOBSOLETEBzip2Data() {
        bitField0_ = (bitField0_ & ~0x00000010);
        oBSOLETEBzip2Data_ = getDefaultInstance().getOBSOLETEBzip2Data();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.mrgeo.vector.mrsvector.pbf.Blob)
    }
    
    static {
      defaultInstance = new Blob(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.mrgeo.vector.mrsvector.pbf.Blob)
  }
  
  public interface BlobHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string type = 1;
    boolean hasType();
    String getType();
    
    // optional bytes indexdata = 2;
    boolean hasIndexdata();
    com.google.protobuf.ByteString getIndexdata();
    
    // required int32 datasize = 3;
    boolean hasDatasize();
    int getDatasize();
  }
  public static final class BlobHeader extends
      com.google.protobuf.GeneratedMessage
      implements BlobHeaderOrBuilder {
    // Use BlobHeader.newBuilder() to construct.
    private BlobHeader(Builder builder) {
      super(builder);
    }
    private BlobHeader(boolean noInit) {}
    
    private static final BlobHeader defaultInstance;
    public static BlobHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public BlobHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.lang.Object type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          type_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes indexdata = 2;
    public static final int INDEXDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString indexdata_;
    public boolean hasIndexdata() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getIndexdata() {
      return indexdata_;
    }
    
    // required int32 datasize = 3;
    public static final int DATASIZE_FIELD_NUMBER = 3;
    private int datasize_;
    public boolean hasDatasize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getDatasize() {
      return datasize_;
    }
    
    private void initFields() {
      type_ = "";
      indexdata_ = com.google.protobuf.ByteString.EMPTY;
      datasize_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDatasize()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, datasize_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTypeBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, indexdata_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, datasize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_fieldAccessorTable;
      }
      
      // Construct using org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        indexdata_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        datasize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.getDescriptor();
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader getDefaultInstanceForType() {
        return org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.getDefaultInstance();
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader build() {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader buildPartial() {
        org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader result = new org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.indexdata_ = indexdata_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.datasize_ = datasize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader) {
          return mergeFrom((org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader other) {
        if (other == org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasIndexdata()) {
          setIndexdata(other.getIndexdata());
        }
        if (other.hasDatasize()) {
          setDatasize(other.getDatasize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasDatasize()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              type_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              indexdata_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              datasize_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string type = 1;
      private java.lang.Object type_ = "";
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setType(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      void setType(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
      }
      
      // optional bytes indexdata = 2;
      private com.google.protobuf.ByteString indexdata_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasIndexdata() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getIndexdata() {
        return indexdata_;
      }
      public Builder setIndexdata(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        indexdata_ = value;
        onChanged();
        return this;
      }
      public Builder clearIndexdata() {
        bitField0_ = (bitField0_ & ~0x00000002);
        indexdata_ = getDefaultInstance().getIndexdata();
        onChanged();
        return this;
      }
      
      // required int32 datasize = 3;
      private int datasize_ ;
      public boolean hasDatasize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getDatasize() {
        return datasize_;
      }
      public Builder setDatasize(int value) {
        bitField0_ |= 0x00000004;
        datasize_ = value;
        onChanged();
        return this;
      }
      public Builder clearDatasize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        datasize_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.mrgeo.vector.mrsvector.pbf.BlobHeader)
    }
    
    static {
      defaultInstance = new BlobHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.mrgeo.vector.mrsvector.pbf.BlobHeader)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mrgeo_core_mrsvector_pbf_Blob_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mrgeo_core_mrsvector_pbf_Blob_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*mrgeo-core/src/main/proto/FileFormat.p" +
      "roto\022\034org.mrgeo.core.mrsvector.pbf\"l\n\004Bl" +
      "ob\022\013\n\003raw\030\001 \001(\014\022\020\n\010raw_size\030\002 \001(\005\022\021\n\tzli" +
      "b_data\030\003 \001(\014\022\021\n\tlzma_data\030\004 \001(\014\022\037\n\023OBSOL" +
      "ETE_bzip2_data\030\005 \001(\014B\002\030\001\"?\n\nBlobHeader\022\014" +
      "\n\004type\030\001 \002(\t\022\021\n\tindexdata\030\002 \001(\014\022\020\n\010datas" +
      "ize\030\003 \002(\005B\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_mrgeo_core_mrsvector_pbf_Blob_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_mrgeo_core_mrsvector_pbf_Blob_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_mrgeo_core_mrsvector_pbf_Blob_descriptor,
              new java.lang.String[] { "Raw", "RawSize", "ZlibData", "LzmaData", "OBSOLETEBzip2Data", },
              org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.class,
              org.mrgeo.vector.mrsvector.pbf.FileFormat.Blob.Builder.class);
          internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_mrgeo_core_mrsvector_pbf_BlobHeader_descriptor,
              new java.lang.String[] { "Type", "Indexdata", "Datasize", },
              org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.class,
              org.mrgeo.vector.mrsvector.pbf.FileFormat.BlobHeader.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
