#!/bin/bash


if [ -n $MRGEO_COMMON_HOME ]; then
  HOME_DIR=$MRGEO_COMMON_HOME
elif [ -n $MRGEO_HOME ]; then
  HOME_DIR=$MRGEO_HOME
  echo "MRGEO_HOME is deprecated, use MRGEO_COMMON_HOME and MRGEO_CONF_DIR instead."
else
  echo "MRGEO_COMMON_HOME not set!"
  exit -1
fi

CMD_JAR=$HOME_DIR/mrgeo-cmd-core*.jar
if [ ! -e $CMD_JAR ]
then
  # could this be a dev environment?

  FILES=`find $HOME_DIR -name "mrgeo-cmd-distribution*.jar"`
  for file in $FILES;
  do
    if [[ $file != *-tests.jar ]]
    then
      CMD_JAR=$file
      break
    fi
  done

  if [ -e $CMD_JAR ]
  then
    LIBS=`dirname $CMD_JAR`:`dirname $CMD_JAR`/lib/*
  else
    echo "Can't find mrgeo-cmd-core jar file.  Make sure MRGEO_COMMON_HOME is set properly"
    exit -1
  fi
else
  LIBS=$HOME_DIR/*:$HOME_DIR/lib/*
fi

#echo $CMD_JAR
#echo $LIBS

# set the hadoop user classpath and force it to be prefixed in the classpath
export HADOOP_USER_CLASSPATH_FIRST=true
export HADOOP_CLASSPATH=$CMD_JAR:$LIBS

# run the command
hadoop jar $CMD_JAR "$@"

